// <auto-generated />
namespace DeckBuilder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class testingcardrelationshipfortraits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testingcardrelationshipfortraits));
        
        string IMigrationMetadata.Id
        {
            get { return "202002141822498_testing-card-relationship-for-traits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
