// <auto-generated />
namespace DeckBuilder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class testingcardrelationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testingcardrelationship));
        
        string IMigrationMetadata.Id
        {
            get { return "202002141820492_testing-card-relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
